-- Bảng "Bệnh Đông y Hiện đại": cấu trúc giống benh_dong_y_excel
-- nhưng KHÔNG có khóa ngoại tới bất kỳ bảng nào.

CREATE TABLE IF NOT EXISTS benh_dong_y_hien_dai (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(120) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  output_cell VARCHAR(20) NOT NULL,
  excel_formula TEXT NOT NULL,
  logic_expression TEXT NOT NULL,
  sql_case_text TEXT NOT NULL,
  sql_case_boolean TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION set_benh_dong_y_hien_dai_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_benh_dong_y_hien_dai_updated_at ON benh_dong_y_hien_dai;
CREATE TRIGGER trg_benh_dong_y_hien_dai_updated_at
BEFORE UPDATE ON benh_dong_y_hien_dai
FOR EACH ROW
EXECUTE FUNCTION set_benh_dong_y_hien_dai_updated_at();
