-- Rebuild hệ thống lịch khám: chuyển sang mô hình slot/vé.
-- BACKUP TRƯỚC KHI CHẠY: file này DROP bảng appointments cũ.
--
-- Mô hình mới:
--   * clinic_schedule_config — singleton (id=1) cấu hình giờ mở/đóng + nghỉ trưa + slot duration.
--   * clinic_day_overrides  — ghi đè cấu hình theo từng ngày (nghỉ lễ, đổi giờ).
--   * appointment_slots     — "vé" 45 phút theo ngày (1 vé = 1 bệnh nhân).
--
-- Cột dùng camelCase để khớp với convention của TypeORM trong project.

BEGIN;

DROP TABLE IF EXISTS appointments CASCADE;

CREATE TABLE IF NOT EXISTS clinic_schedule_config (
  id INT PRIMARY KEY,
  "openTime" TIME NOT NULL,
  "closeTime" TIME NOT NULL,
  "breakStart" TIME,
  "breakEnd" TIME,
  "slotDurationMinutes" INT NOT NULL DEFAULT 45,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT clinic_schedule_config_singleton CHECK (id = 1)
);

INSERT INTO clinic_schedule_config (id, "openTime", "closeTime", "breakStart", "breakEnd", "slotDurationMinutes")
VALUES (1, '08:00', '17:00', '12:00', '13:30', 45)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS clinic_day_overrides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" DATE NOT NULL UNIQUE,
  "isClosed" BOOLEAN NOT NULL DEFAULT FALSE,
  "openTime" TIME,
  "closeTime" TIME,
  "breakStart" TIME,
  "breakEnd" TIME,
  note TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS appointment_slots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "slotDate" DATE NOT NULL,
  "slotTime" TIME NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  "patientId" INT,
  reason TEXT,
  notes TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT appointment_slots_status_check
    CHECK (status IN ('OPEN', 'CLOSED', 'BOOKED', 'COMPLETED', 'CANCELLED')),
  CONSTRAINT appointment_slots_unique_slot UNIQUE ("slotDate", "slotTime")
);

CREATE INDEX IF NOT EXISTS idx_appointment_slots_date ON appointment_slots ("slotDate");
CREATE INDEX IF NOT EXISTS idx_appointment_slots_patient ON appointment_slots ("patientId");

CREATE OR REPLACE FUNCTION set_updated_at_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updatedAt" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_clinic_schedule_config_updated_at ON clinic_schedule_config;
CREATE TRIGGER trg_clinic_schedule_config_updated_at
BEFORE UPDATE ON clinic_schedule_config
FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_clinic_day_overrides_updated_at ON clinic_day_overrides;
CREATE TRIGGER trg_clinic_day_overrides_updated_at
BEFORE UPDATE ON clinic_day_overrides
FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_appointment_slots_updated_at ON appointment_slots;
CREATE TRIGGER trg_appointment_slots_updated_at
BEFORE UPDATE ON appointment_slots
FOR EACH ROW EXECUTE FUNCTION set_updated_at_timestamp();

COMMIT;
