-- SQL ĐÃ GIẢI KHỚP theo id thực của DB (sinh từ resolve_apply.js). Áp dụng 1 lần.
BEGIN;
INSERT INTO benh_cau_thanh (compound_id, component_id, thu_tu) VALUES
  (39, 38, 1)
ON CONFLICT (compound_id, component_id) DO NOTHING;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='cặp nguyên lạc, tăng men tiêu hoá, hấp thụ dinh dưỡng' WHERE id_phac_do=12;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='cặp nguyên lạc, tăng men tiêu hoá, hấp thụ dinh dưỡng' WHERE id_phac_do=13;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='làm khoẻ tuyến tuỵ, tăng vận hoá Tỳ' WHERE id_phac_do=14;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='làm khoẻ tuyến tuỵ, tăng vận hoá Tỳ' WHERE id_phac_do=16;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='cặp nguyên lạc, tăng men tiêu hoá, hấp thụ dinh dưỡng' WHERE id_phac_do=18;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='cặp nguyên lạc, tăng men tiêu hoá, hấp thụ dinh dưỡng' WHERE id_phac_do=19;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='làm khoẻ tuyến tuỵ, tăng vận hoá Tỳ' WHERE id_phac_do=23;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='làm khoẻ tuyến tuỵ, tăng vận hoá Tỳ' WHERE id_phac_do=21;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tăng dương khí, sát khuẩn đường ruột' WHERE id_phac_do=25;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='cặp nguyên lạc, tăng men tiêu hoá, hấp thụ dinh dưỡng' WHERE id_phac_do=42;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='cặp nguyên lạc, tăng men tiêu hoá, hấp thụ dinh dưỡng' WHERE id_phac_do=43;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='làm khoẻ tuyến tuỵ, tăng vận hoá Tỳ' WHERE id_phac_do=47;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='làm khoẻ tuyến tuỵ, tăng vận hoá Tỳ' WHERE id_phac_do=45;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tăng dương khí, sát khuẩn đường ruột' WHERE id_phac_do=49;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='nhóm huyệt kinh nghiệm trị thấp tim' WHERE id_phac_do=36;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='nhóm huyệt kinh nghiệm trị thấp tim' WHERE id_phac_do=37;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='nhóm huyệt kinh nghiệm trị thấp tim' WHERE id_phac_do=38;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='nhóm huyệt kinh nghiệm trị thấp tim' WHERE id_phac_do=39;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tăng thân nhiệt, hỗ trợ tuần hoàn huyết dịch' WHERE id_phac_do=40;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tăng thân nhiệt, hỗ trợ tuần hoàn huyết dịch' WHERE id_phac_do=41;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tứ hoa liệu pháp, chữa lao do âm hư' WHERE id_phac_do=89;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chủ huyệt trị âm huyết hao tổn' WHERE id_phac_do=91;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả hư nhiệt Tâm, an thần định chí' WHERE id_phac_do=92;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả hoả ở Phế, Đảm, giữ chân âm' WHERE id_phac_do=93;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả hoả ở Phế, Đảm, giữ chân âm' WHERE id_phac_do=94;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tứ hoa liệu pháp, chữa lao do âm hư' WHERE id_phac_do=607;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chủ huyệt trị âm huyết hao tổn' WHERE id_phac_do=609;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả hư nhiệt Tâm, an thần định chí' WHERE id_phac_do=610;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả hoả ở Phế, Đảm, giữ chân âm' WHERE id_phac_do=611;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả hoả ở Phế, Đảm, giữ chân âm' WHERE id_phac_do=612;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='mạnh sinh huyết, tàng huyết Can Tỳ' WHERE id_phac_do=95;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='mạnh sinh huyết, tàng huyết Can Tỳ' WHERE id_phac_do=613;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='mạnh sinh huyết, tàng huyết Can Tỳ' WHERE id_phac_do=96;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='mạnh sinh huyết, tàng huyết Can Tỳ' WHERE id_phac_do=614;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chích nặn máu, giải co thắt cơ tim, mạch vành' WHERE id_phac_do=98;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='khứ ứ kết ở Đảm, hành khí hành huyết' WHERE id_phac_do=100;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='thông kinh hoạt lạc' WHERE id_phac_do=101;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='thông kinh hoạt lạc' WHERE id_phac_do=102;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả Can hoả, dứt nguồn sinh phong' WHERE id_phac_do=103;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả Can hoả, dứt nguồn sinh phong' WHERE id_phac_do=104;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả nhiệt ở Tâm làm thần chí tán loạn' WHERE id_phac_do=105;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả nhiệt ở Tâm làm thần chí tán loạn' WHERE id_phac_do=106;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả nhiệt ở Tâm làm thần chí tán loạn' WHERE id_phac_do=107;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='giải phong tả nhiệt ở gân bắp trị thao cuồng' WHERE id_phac_do=108;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='giải phong tả nhiệt ở gân bắp trị thao cuồng' WHERE id_phac_do=109;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='khai khiếu tinh thần, cấp cứu choáng ngất' WHERE id_phac_do=110;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='khai khiếu tinh thần, cấp cứu choáng ngất' WHERE id_phac_do=111;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='khai khiếu tinh thần, cấp cứu choáng ngất' WHERE id_phac_do=112;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tỉnh huyệt kinh Tâm bào, giải tà khí ở Tâm' WHERE id_phac_do=113;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị Tâm hoả cang thịnh gây nứt, sưng lưỡi' WHERE id_phac_do=558;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị Tâm hoả cang thịnh gây nứt, sưng lưỡi' WHERE id_phac_do=559;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa lưỡi sưng đau' WHERE id_phac_do=560;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa lưỡi sưng đau' WHERE id_phac_do=561;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tỉnh huyệt, trừ nhiệt kinh Tiểu trường và Bàng quang' WHERE id_phac_do=555;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị nhiệt làm khí không hoá, đái máu, đái buốt' WHERE id_phac_do=556;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị nhiệt làm khí không hoá, đái máu, đái buốt' WHERE id_phac_do=557;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả mộc khí Can kinh, trị đau co thắt bụng dưới' WHERE id_phac_do=119;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả mộc khí Can kinh, trị đau co thắt bụng dưới' WHERE id_phac_do=528;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị cơn đau quặn dọc cơ thẳng bụng' WHERE id_phac_do=120;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị cơn đau quặn dọc cơ thẳng bụng' WHERE id_phac_do=529;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị cơn đau quặn dọc cơ thẳng bụng' WHERE id_phac_do=121;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị cơn đau quặn dọc cơ thẳng bụng' WHERE id_phac_do=530;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị cơn đau quặn dọc cơ thẳng bụng' WHERE id_phac_do=122;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị cơn đau quặn dọc cơ thẳng bụng' WHERE id_phac_do=531;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='khai khí uất ở lồng ngực' WHERE id_phac_do=123;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='sơ can lý khí' WHERE id_phac_do=124;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='sơ can lý khí' WHERE id_phac_do=125;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa đau vỏ lồng ngực' WHERE id_phac_do=126;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='dẫn hoả đi xuống' WHERE id_phac_do=127;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ Can Tỳ khí, phá gốc bĩ, chữa gan lách sưng to' WHERE id_phac_do=128;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ Can Tỳ khí, phá gốc bĩ, chữa gan lách sưng to' WHERE id_phac_do=129;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ Can Tỳ khí, phá gốc bĩ, chữa gan lách sưng to' WHERE id_phac_do=130;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='hoãn giải động mạch não' WHERE id_phac_do=438;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='hoãn giải động mạch não' WHERE id_phac_do=439;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Chữa cao huyết áp' WHERE id_phac_do=399;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Chữa cao huyết áp' WHERE id_phac_do=400;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Chữa cao huyết áp' WHERE id_phac_do=401;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Chữa cao huyết áp' WHERE id_phac_do=402;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Chữa cao huyết áp; thuỷ châm' WHERE id_phac_do=403;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Chữa cao huyết áp; thuỷ châm' WHERE id_phac_do=404;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Chữa cao huyết áp' WHERE id_phac_do=405;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Chữa cao huyết áp; thuỷ châm' WHERE id_phac_do=406;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Chữa cao huyết áp' WHERE id_phac_do=527;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Cổ gáy cứng đau, đau đầu cứng gáy' WHERE id_phac_do=374;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Cổ gáy cứng đau, đau đầu cứng gáy' WHERE id_phac_do=375;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Cổ gáy không xoay được' WHERE id_phac_do=376;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tả, chữa đầu không quay trái phải' WHERE id_phac_do=377;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Sái cổ, cứng gáy' WHERE id_phac_do=378;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Sái cổ, căng gáy đầu' WHERE id_phac_do=379;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Bị lạnh mà cứng cổ gáy' WHERE id_phac_do=501;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Bị lạnh mà cứng cổ gáy' WHERE id_phac_do=380;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Đau gáy đầu' WHERE id_phac_do=381;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Sái cổ' WHERE id_phac_do=382;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Sái cổ' WHERE id_phac_do=383;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Đau lưng, thận hư' WHERE id_phac_do=440;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Đau lưng, thận hư' WHERE id_phac_do=442;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Đau lưng (huyệt chính)' WHERE id_phac_do=443;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Phong thấp hàn, viêm cột sống' WHERE id_phac_do=444;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Đau lưng không cúi ngửa được' WHERE id_phac_do=445;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Phong thấp hàn đau lưng' WHERE id_phac_do=441;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Thận hư đau lưng' WHERE id_phac_do=446;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Bong gân cấp, đau sát thắt lưng' WHERE id_phac_do=447;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Đau sát thắt lưng, bong gân cấp' WHERE id_phac_do=450;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Nhĩ châm đau lưng' WHERE id_phac_do=449;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Đau lưng' WHERE id_phac_do=451;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Đau lưng' WHERE id_phac_do=452;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Đau lưng' WHERE id_phac_do=453;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Đau lưng' WHERE id_phac_do=454;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Đau lưng, khó động đậy' WHERE id_phac_do=455;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Đau lưng khó động đậy' WHERE id_phac_do=470;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Lưng trên dưới đau' WHERE id_phac_do=456;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Lưng trên dưới đau' WHERE id_phac_do=457;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Đau thắt lưng, không cúi ngửa' WHERE id_phac_do=458;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Cột sống cứng cấp tính' WHERE id_phac_do=460;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Cột sống cứng cấp tính' WHERE id_phac_do=461;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Cột sống gãy ngược, thoát vị đĩa đệm' WHERE id_phac_do=462;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Cột sống gãy ngược lại' WHERE id_phac_do=463;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Viêm cột sống phong thấp, còng gù lưng' WHERE id_phac_do=464;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Viêm cột sống do phong thấp' WHERE id_phac_do=465;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Viêm cột sống do phong thấp' WHERE id_phac_do=466;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Viêm cột sống do phong thấp' WHERE id_phac_do=467;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Viêm cột sống do phong thấp' WHERE id_phac_do=468;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Cột sống cứng cấp; viêm cột sống' WHERE id_phac_do=459;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Lưng trên liền lưng dưới đau' WHERE id_phac_do=469;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tổn thương phần mềm thắt lưng' WHERE id_phac_do=471;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tổn thương phần mềm; còng gù lưng' WHERE id_phac_do=472;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Phong lao đau lưng' WHERE id_phac_do=473;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Phong lao đau lưng' WHERE id_phac_do=474;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Đau lưng đùi, xương cùng' WHERE id_phac_do=475;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Lưng đùi đau, đau khớp hông' WHERE id_phac_do=476;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Lưng đùi đau, đau khớp hông' WHERE id_phac_do=477;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Còng gù lưng (cứu)' WHERE id_phac_do=478;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Còng gù do mềm xương' WHERE id_phac_do=479;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Lưng còng khom' WHERE id_phac_do=480;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Lưng còng khom' WHERE id_phac_do=481;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Bong gân cấp vùng lưng' WHERE id_phac_do=482;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Bệnh vùng thắt lưng, xương sống' WHERE id_phac_do=483;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa đau đầu do can hoả' WHERE id_phac_do=131;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa đau đầu do can hoả' WHERE id_phac_do=132;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='làm giảm huyết áp' WHERE id_phac_do=133;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trấn kinh, chống co quắp co giật' WHERE id_phac_do=134;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trấn kinh, chống co quắp co giật' WHERE id_phac_do=135;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='dẫn hoả đi xuống' WHERE id_phac_do=136;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tư thận âm, chế Can hoả' WHERE id_phac_do=137;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa liệt nửa người' WHERE id_phac_do=138;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa liệt nửa người' WHERE id_phac_do=139;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa liệt nửa người' WHERE id_phac_do=140;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ âm' WHERE id_phac_do=532;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ tâm huyết' WHERE id_phac_do=534;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ Tỳ, tăng vận hoá' WHERE id_phac_do=535;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ Tỳ, tăng vận hoá' WHERE id_phac_do=536;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ thận âm' WHERE id_phac_do=537;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ thận âm' WHERE id_phac_do=538;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='làm gân cơ chi dưới vững chắc' WHERE id_phac_do=539;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị Đảm nhiệt' WHERE id_phac_do=247;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị Đảm nhiệt' WHERE id_phac_do=149;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị Đảm nhiệt' WHERE id_phac_do=249;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị Đảm nhiệt' WHERE id_phac_do=151;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả hoả ở Can Đảm, liên sườn' WHERE id_phac_do=152;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='điều hoà công năng nội tạng' WHERE id_phac_do=252;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='điều hoà công năng nội tạng' WHERE id_phac_do=154;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tăng hấp thụ dinh dưỡng' WHERE id_phac_do=155;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tăng hấp thụ dinh dưỡng' WHERE id_phac_do=156;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tăng công năng tuyến tuỵ' WHERE id_phac_do=157;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tăng công năng tuyến tuỵ' WHERE id_phac_do=158;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tăng công năng tuyến tuỵ' WHERE id_phac_do=236;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tăng công năng tuyến tuỵ' WHERE id_phac_do=159;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ tỳ vị' WHERE id_phac_do=160;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ tỳ vị' WHERE id_phac_do=232;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ tỳ vị' WHERE id_phac_do=161;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ tỳ vị' WHERE id_phac_do=234;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ tỳ vị' WHERE id_phac_do=162;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ tỳ vị' WHERE id_phac_do=235;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ công năng tỳ vị' WHERE id_phac_do=164;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ công năng tỳ vị' WHERE id_phac_do=165;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='đại bổ nguyên khí' WHERE id_phac_do=493;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bồi bổ âm huyết' WHERE id_phac_do=166;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bồi bổ âm huyết' WHERE id_phac_do=169;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ tỳ vị, vận hoá thấp trọc' WHERE id_phac_do=170;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ tỳ vị, vận hoá thấp trọc' WHERE id_phac_do=171;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='vận Tỳ hoá thấp ở đầu mặt' WHERE id_phac_do=175;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='vận Tỳ hoá thấp ở đầu mặt' WHERE id_phac_do=176;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa ngại nói ham nằm do thấp khốn' WHERE id_phac_do=177;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tứ hoa, bồi bổ cả khí và huyết' WHERE id_phac_do=179;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Trị chứng hay quên' WHERE id_phac_do=180;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Bổ Tâm, biểu lý với Tiểu trường' WHERE id_phac_do=182;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Biểu lý Tiểu trường, giúp Tâm khoẻ' WHERE id_phac_do=183;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Bổ trực tiếp vào Tỳ Vị' WHERE id_phac_do=184;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Bổ trực tiếp vào Tỳ Vị' WHERE id_phac_do=185;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Bổ trực tiếp vào Tỳ Vị' WHERE id_phac_do=186;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Trị chứng hay quên' WHERE id_phac_do=187;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Trực tiếp bổ thận' WHERE id_phac_do=188;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Trực tiếp bổ thận' WHERE id_phac_do=189;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Bổ thận dương, cầm ỉa chảy' WHERE id_phac_do=190;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Bổ thận dương, ấm ngũ tạng' WHERE id_phac_do=191;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tăng cường vận hoá của Tỳ' WHERE id_phac_do=192;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Bổ dưỡng khí huyết' WHERE id_phac_do=193;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Cứu ngăn cơn suyễn, ấm lưng' WHERE id_phac_do=195;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Trị chứng ngại nói, ham nằm' WHERE id_phac_do=196;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Trị chứng ngại nói, ham nằm' WHERE id_phac_do=197;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tả nhiệt vùng trước trán' WHERE id_phac_do=565;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tả nhiệt vùng trước trán' WHERE id_phac_do=566;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tả nhiệt vùng trước trán' WHERE id_phac_do=567;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tả nhiệt vùng trước trán' WHERE id_phac_do=568;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Hạ nhiệt, dẫn hoả xuống, dứt phiền thao' WHERE id_phac_do=569;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Hạ nhiệt, dẫn hoả xuống, dứt phiền thao' WHERE id_phac_do=570;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Trị xuất huyết dạ dày, thổ huyết' WHERE id_phac_do=576;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Cầm chảy máu mũi (nục huyết)' WHERE id_phac_do=577;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Cầm chảy máu mũi (nục huyết)' WHERE id_phac_do=578;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Chữa vòm miệng, lợi răng sưng đau' WHERE id_phac_do=574;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Chữa vòm miệng, lợi răng sưng đau' WHERE id_phac_do=575;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tả nhiệt vùng trước trán' WHERE id_phac_do=593;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tả nhiệt vùng trước trán' WHERE id_phac_do=594;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tả nhiệt vùng trước trán' WHERE id_phac_do=595;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tả nhiệt vùng trước trán' WHERE id_phac_do=596;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Hạ nhiệt, dẫn hoả xuống, dứt phiền thao' WHERE id_phac_do=597;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Hạ nhiệt, dẫn hoả xuống, dứt phiền thao' WHERE id_phac_do=598;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Bổ âm, trừ hư hoả' WHERE id_phac_do=600;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Bổ âm, trừ hư hoả' WHERE id_phac_do=601;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Trị riêng chứng Can' WHERE id_phac_do=224;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Trị riêng chứng Can' WHERE id_phac_do=225;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Phương huyệt truyền thống trị đau dạ dày' WHERE id_phac_do=226;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Cầu nối, trị chung vùng bụng trên' WHERE id_phac_do=227;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Phương huyệt truyền thống trị đau dạ dày' WHERE id_phac_do=228;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Phương huyệt truyền thống trị đau dạ dày' WHERE id_phac_do=229;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tả khi nôn ra máu' WHERE id_phac_do=230;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tả khi nôn ra máu' WHERE id_phac_do=231;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='đặc trị tiết dịch xoang sau' WHERE id_phac_do=261;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='đặc trị tiết dịch xoang sau' WHERE id_phac_do=262;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='đặc trị tiết dịch xoang sau' WHERE id_phac_do=498;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='cắt cơn suyễn' WHERE id_phac_do=263;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa viêm phế quản có đờm' WHERE id_phac_do=264;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa viêm phế quản có đờm' WHERE id_phac_do=265;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị giãn phế quản, đờm có máu' WHERE id_phac_do=267;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị giãn phế quản, đờm có máu' WHERE id_phac_do=268;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='làm ấm Phế tạng, đuổi hàn tà' WHERE id_phac_do=579;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='làm ấm Phế tạng, đuổi hàn tà' WHERE id_phac_do=580;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='nâng sức nóng, giúp Phế khí túc giáng' WHERE id_phac_do=581;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='làm ấm kinh Bàng quang, cắt cơn hen' WHERE id_phac_do=582;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ khí, hoá đàm hàn' WHERE id_phac_do=583;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ khí, hoá đàm hàn' WHERE id_phac_do=584;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chích nặn máu hạ nhiệt nhiều tạng' WHERE id_phac_do=585;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='nặn máu hạ nhiệt trường Vị' WHERE id_phac_do=586;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='khích huyệt Phế, trị bệnh cấp tính' WHERE id_phac_do=587;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tác dụng gần nhất với phế tạng' WHERE id_phac_do=588;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả bớt dương khí hữu dư để mát' WHERE id_phac_do=589;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='mộ huyệt Phế, tả tà nhiệt hữu dư' WHERE id_phac_do=590;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả Can hoả phản khắc Phế kim' WHERE id_phac_do=591;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ để dẫn hoả đi xuống' WHERE id_phac_do=592;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='cứu ôn bổ phế tạng' WHERE id_phac_do=283;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ khí, tăng thúc đẩy Phế khí' WHERE id_phac_do=284;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tứ hoa, bổ phế khí và khí hoá' WHERE id_phac_do=285;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='khí Tỳ khoẻ hỗ trợ Phế khí' WHERE id_phac_do=287;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='khí Thận khoẻ hỗ trợ Phế khí' WHERE id_phac_do=288;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='giữ gìn nguyên khí toàn thân' WHERE id_phac_do=289;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='giữ gìn nguyên khí toàn thân' WHERE id_phac_do=290;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bồi bổ âm huyết, huyết sinh khí' WHERE id_phac_do=291;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tứ hoa, bồi bổ khí huyết, chống suy nhược' WHERE id_phac_do=292;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tư âm giáng hoả' WHERE id_phac_do=294;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ Phế' WHERE id_phac_do=295;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả hư hoả ở Can' WHERE id_phac_do=296;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả hư hoả ở Can' WHERE id_phac_do=297;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị giãn phế quản xuất huyết' WHERE id_phac_do=298;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị giãn phế quản xuất huyết' WHERE id_phac_do=299;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='dẫn hoả xuống, bồi thổ sinh kim' WHERE id_phac_do=300;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ âm ở Can Tỳ Thận' WHERE id_phac_do=301;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trực tiếp bổ vào Phế tạng' WHERE id_phac_do=302;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ Tỳ để bổ phế, bồi thổ sinh kim' WHERE id_phac_do=303;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tứ hoa, bổ dưỡng khí huyết toàn thân' WHERE id_phac_do=305;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='nguyên lạc biểu lý, bổ Tâm khí' WHERE id_phac_do=307;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='nguyên lạc biểu lý, bổ Tâm khí' WHERE id_phac_do=308;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ vào âm huyết' WHERE id_phac_do=309;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ Tỳ để bổ phế, bồi thổ sinh kim' WHERE id_phac_do=310;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tứ hoa, chữa lao phổi hiệu quả' WHERE id_phac_do=540;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ Phế âm' WHERE id_phac_do=542;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ thận âm' WHERE id_phac_do=543;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả Can Đảm hoả vượng' WHERE id_phac_do=544;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tả Can Đảm hoả vượng' WHERE id_phac_do=545;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ âm huyết' WHERE id_phac_do=546;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ âm huyết' WHERE id_phac_do=547;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='dẫn hoả khí đi xuống' WHERE id_phac_do=548;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='cầm mồ hôi, giữ âm tân' WHERE id_phac_do=549;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='cầm mồ hôi, giữ âm tân' WHERE id_phac_do=550;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='nguyên huyệt, hạ nhiệt và khử thấp Đại trường' WHERE id_phac_do=320;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='lạc huyệt, khử ngoại tà ở tam tiêu' WHERE id_phac_do=321;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='kiện tỳ, hoà vị, hoá thấp' WHERE id_phac_do=322;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='hạ hợp huyệt, trị bệnh Đại trường mạnh nhất' WHERE id_phac_do=323;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Tứ hoa liệu pháp chữa chứng âm hư' WHERE id_phac_do=324;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa đau đầu do thần kinh suy nhược' WHERE id_phac_do=500;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa đau đầu do thần kinh suy nhược' WHERE id_phac_do=326;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ thận, chữa đau lưng, di tinh' WHERE id_phac_do=327;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ âm huyết' WHERE id_phac_do=328;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ âm huyết' WHERE id_phac_do=329;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ âm huyết' WHERE id_phac_do=330;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trừ đau đầu, ù tai hoa mắt do Thận âm hư' WHERE id_phac_do=331;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trừ đau đầu, ù tai hoa mắt do Thận âm hư' WHERE id_phac_do=332;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trừ đau đầu, ù tai hoa mắt do Thận âm hư' WHERE id_phac_do=333;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị choáng tiền đình, phân lỏng do Thận dương hư' WHERE id_phac_do=334;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị choáng tiền đình, phân lỏng do Thận dương hư' WHERE id_phac_do=335;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='nâng thân nhiệt, cắt cơn hen suyễn' WHERE id_phac_do=336;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tăng công năng Phế, Đảm, tăng dương khí toàn thân' WHERE id_phac_do=337;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ tỳ thận, ấm lưng, chữa lưng gối mỏi đau' WHERE id_phac_do=339;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ tỳ thận, ấm lưng, chữa lưng gối mỏi đau' WHERE id_phac_do=340;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ tỳ thận, ấm lưng, chữa lưng gối mỏi đau' WHERE id_phac_do=341;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị đái không bình thường do khí hoá' WHERE id_phac_do=342;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='đại bổ nguyên khí, khí dương' WHERE id_phac_do=343;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị liệt dương' WHERE id_phac_do=344;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị liệt dương' WHERE id_phac_do=345;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị liệt dương' WHERE id_phac_do=346;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bồi bổ âm huyết, âm tinh' WHERE id_phac_do=347;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bồi bổ âm huyết, âm tinh' WHERE id_phac_do=348;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bồi bổ âm huyết, âm tinh' WHERE id_phac_do=349;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bồi bổ âm huyết, âm tinh' WHERE id_phac_do=350;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ tâm âm, chữa hồi hộp, mạch nhanh' WHERE id_phac_do=351;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ tâm âm, chữa hồi hộp, mạch nhanh' WHERE id_phac_do=352;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='bổ Thận âm, an thần dễ ngủ' WHERE id_phac_do=353;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='tăng tâm lực, trí nhớ' WHERE id_phac_do=354;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='Thận thuỷ chế Tâm hoả, khai khiếu tỉnh thần' WHERE id_phac_do=355;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='khí hoá được thông hoạt' WHERE id_phac_do=356;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='khử tà nhiệt ở bàng quang' WHERE id_phac_do=357;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa sỏi thận, niệu quản, bàng quang' WHERE id_phac_do=358;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa sỏi thận, niệu quản, bàng quang' WHERE id_phac_do=359;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='mộ huyệt bàng quang, trị mọi bệnh bàng quang' WHERE id_phac_do=360;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị viêm cấp tính tiền liệt tuyến' WHERE id_phac_do=361;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị viêm cấp tính tiền liệt tuyến' WHERE id_phac_do=362;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='đặc trị bệnh tiền liệt tuyến' WHERE id_phac_do=364;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị bệnh nhị âm, chữa bí đái ỉa' WHERE id_phac_do=365;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='điều chỉnh công năng tạng phủ qua bối du huyệt' WHERE id_phac_do=366;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='điều chỉnh công năng tạng phủ qua bối du huyệt' WHERE id_phac_do=368;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='điều chỉnh công năng tạng phủ qua bối du huyệt' WHERE id_phac_do=369;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='huyệt chữa bệnh dạ dày truyền thống' WHERE id_phac_do=370;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='huyệt chữa bệnh dạ dày truyền thống' WHERE id_phac_do=371;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='huyệt chữa bệnh dạ dày truyền thống' WHERE id_phac_do=372;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='huyệt chữa bệnh dạ dày truyền thống' WHERE id_phac_do=373;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa dị ứng mẩn ngứa' WHERE id_phac_do=384;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa dị ứng mẩn ngứa' WHERE id_phac_do=385;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa dị ứng mẩn ngứa' WHERE id_phac_do=386;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa dị ứng mẩn ngứa' WHERE id_phac_do=387;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chủ trị dị ứng mẩn ngứa mạn tính' WHERE id_phac_do=388;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa dị ứng kèm đau bụng, ỉa chảy' WHERE id_phac_do=389;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa ngực buồn bằn, thở gấp' WHERE id_phac_do=390;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa ngực buồn bằn, thở gấp' WHERE id_phac_do=391;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='nhĩ châm chữa dị ứng' WHERE id_phac_do=392;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa dị ứng mẩn ngứa' WHERE id_phac_do=393;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa dị ứng mẩn ngứa' WHERE id_phac_do=394;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa dị ứng mẩn ngứa' WHERE id_phac_do=395;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa phong chẩn' WHERE id_phac_do=396;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa dị ứng mẩn ngứa' WHERE id_phac_do=397;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='chữa dị ứng, quá mẫn cảm viêm da' WHERE id_phac_do=398;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='huyệt phương chủ, kích thích mạnh ra mồ hôi' WHERE id_phac_do=502;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='huyệt phương chủ, kích thích mạnh ra mồ hôi' WHERE id_phac_do=503;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='huyệt phương chủ, kích thích mạnh ra mồ hôi' WHERE id_phac_do=504;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị tắc mũi' WHERE id_phac_do=505;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị toàn thân đau buốt, sốt cao' WHERE id_phac_do=506;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị toàn thân đau buốt' WHERE id_phac_do=507;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị sốt cao' WHERE id_phac_do=508;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị sốt cao' WHERE id_phac_do=509;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị đầu đau dữ dội' WHERE id_phac_do=510;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị đầu đau dữ dội' WHERE id_phac_do=511;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị ho hắng' WHERE id_phac_do=512;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị ho hắng' WHERE id_phac_do=513;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị ho hắng' WHERE id_phac_do=514;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị ho hắng' WHERE id_phac_do=515;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị họng đau' WHERE id_phac_do=516;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị họng đau, chích ra máu' WHERE id_phac_do=517;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị quặn bụng buồn nôn' WHERE id_phac_do=518;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị cảm mạo' WHERE id_phac_do=519;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị cảm mạo' WHERE id_phac_do=520;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị cảm mạo' WHERE id_phac_do=521;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị cảm mạo' WHERE id_phac_do=522;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị ho hắng, viêm phổi' WHERE id_phac_do=523;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị ngoại cảm sốt cao' WHERE id_phac_do=524;
UPDATE phac_do_dieu_tri SET y_nghia_huyet='trị ngoại cảm sốt cao' WHERE id_phac_do=525;
COMMIT;