-- ==========================================================================
-- SEED ĐẦY ĐỦ — Ý nghĩa từng huyệt + Gộp thể kép (cascade) cho 84 chứng
-- Sinh tự động từ giải nghĩa phương huyệt (import-legacy-meridian-syndromes.sql).
-- Chạy SAU add-phac-do-y-nghia-and-benh-cau-thanh.sql. An toàn chạy lại nhiều lần.
-- Khớp CHỨNG theo benh_dong_y.tieuket (ILIKE); khớp HUYỆT theo huyet_vi.ten_huyet (ILIKE).
-- Dòng nào tên không khớp DB thật (lệch dấu/chính tả) sẽ là no-op — rà bằng 2 query cuối file.
-- CHỈ thêm gộp cho chứng "cascade" (mượn toàn bộ phương huyệt thể khác); thể tự-chứa giữ nguyên.
-- ==========================================================================

BEGIN;

-- (A) GỘP THỂ KÉP / CASCADE — 1 liên kết
INSERT INTO benh_cau_thanh (compound_id, component_id, thu_tu, ghi_chu)
SELECT c.id, m.id, v.thu_tu, NULL
FROM (VALUES
  ('Thận âm dương lưỡng hư', 'Thận dương hư', 1)
) AS v(compound_name, component_name, thu_tu)
JOIN benh_dong_y c ON c.tieuket ILIKE v.compound_name
JOIN benh_dong_y m ON m.tieuket ILIKE v.component_name || '%'
ON CONFLICT (compound_id, component_id) DO NOTHING;

-- (B) Ý NGHĨA TỪNG HUYỆT — 492 dòng (chỉ cập nhật dòng phác đồ đã có)
UPDATE phac_do_dieu_tri p
SET y_nghia_huyet = v.y_nghia
FROM (VALUES
  ('Tâm dương bất túc - Tâm khí hư', 'Thần môn', 'Cặp nguyên lạc, tăng men tiêu hoá, hấp thụ dinh dưỡng'),
  ('Tâm dương bất túc - Tâm khí hư', 'Chi chính', 'Cặp nguyên lạc, tăng men tiêu hoá, hấp thụ dinh dưỡng'),
  ('Tâm dương bất túc - Tâm khí hư', 'Tụy du', 'Làm khoẻ tuyến tuỵ, tăng vận hoá Tỳ'),
  ('Tâm dương bất túc - Tâm khí hư', 'Ý xá', 'Làm khoẻ tuyến tuỵ, tăng vận hoá Tỳ'),
  ('Tâm dương bất túc - Tâm dương hư', 'Thần môn', 'Cặp nguyên lạc, tăng men tiêu hoá, hấp thụ dinh dưỡng'),
  ('Tâm dương bất túc - Tâm dương hư', 'Chi chính', 'Cặp nguyên lạc, tăng men tiêu hoá, hấp thụ dinh dưỡng'),
  ('Tâm dương bất túc - Tâm dương hư', 'Tụy du', 'Làm khoẻ tuyến tuỵ, tăng vận hoá Tỳ'),
  ('Tâm dương bất túc - Tâm dương hư', 'Ý xá', 'Làm khoẻ tuyến tuỵ, tăng vận hoá Tỳ'),
  ('Tâm dương bất túc - Tâm dương hư', 'Đảm du', 'Tăng dương khí, sát khuẩn đường ruột'),
  ('Tâm dương bất túc - Tâm dương hư', 'Dương cương', 'Tăng dương khí, sát khuẩn đường ruột'),
  ('Tâm dương bất túc - Tâm dương hư suy', 'Thần môn', 'Cặp nguyên lạc, tăng men tiêu hoá, hấp thụ dinh dưỡng'),
  ('Tâm dương bất túc - Tâm dương hư suy', 'Chi chính', 'Cặp nguyên lạc, tăng men tiêu hoá, hấp thụ dinh dưỡng'),
  ('Tâm dương bất túc - Tâm dương hư suy', 'Tụy du', 'Làm khoẻ tuyến tuỵ, tăng vận hoá Tỳ'),
  ('Tâm dương bất túc - Tâm dương hư suy', 'Ý xá', 'Làm khoẻ tuyến tuỵ, tăng vận hoá Tỳ'),
  ('Tâm dương bất túc - Tâm dương hư suy', 'Đảm du', 'Tăng dương khí, sát khuẩn đường ruột'),
  ('Tâm dương bất túc - Tâm dương hư suy', 'Dương cương', 'Tăng dương khí, sát khuẩn đường ruột'),
  ('Tâm dương bất túc - Tâm dương hư suy', 'Đại chùy', 'Nhóm huyệt kinh nghiệm trị thấp tim'),
  ('Tâm dương bất túc - Tâm dương hư suy', 'Trung phủ', 'Nhóm huyệt kinh nghiệm trị thấp tim'),
  ('Tâm dương bất túc - Tâm dương hư suy', 'Đản trung', 'Nhóm huyệt kinh nghiệm trị thấp tim'),
  ('Tâm dương bất túc - Tâm dương hư suy', 'Du phủ', 'Nhóm huyệt kinh nghiệm trị thấp tim'),
  ('Tâm dương bất túc - Tâm dương hư suy', 'Thái khê', 'Tăng thân nhiệt, hỗ trợ tuần hoàn huyết dịch'),
  ('Tâm dương bất túc - Tâm dương hư suy', 'Côn lôn', 'Tăng thân nhiệt, hỗ trợ tuần hoàn huyết dịch'),
  ('Tâm âm bất túc - Tâm âm hư', 'Cách du', 'Tứ hoa liệu pháp, chữa lao do âm hư'),
  ('Tâm âm bất túc - Tâm âm hư', 'Đảm du', 'Tứ hoa liệu pháp, chữa lao do âm hư'),
  ('Tâm âm bất túc - Tâm âm hư', 'Nội quan', 'Chủ huyệt trị âm huyết hao tổn'),
  ('Tâm âm bất túc - Tâm âm hư', 'Thần môn', 'Tả hư nhiệt Tâm, an thần định chí'),
  ('Tâm âm bất túc - Tâm âm hư', 'Chí dương', 'Tả hoả ở Phế, Đảm, giữ chân âm'),
  ('Tâm âm bất túc - Tâm âm hư', 'Phế du', 'Tả hoả ở Phế, Đảm, giữ chân âm'),
  ('Tâm âm bất túc - Tâm huyết hư', 'Cách du', 'Tứ hoa liệu pháp, chữa lao do âm hư'),
  ('Tâm âm bất túc - Tâm huyết hư', 'Đảm du', 'Tứ hoa liệu pháp, chữa lao do âm hư'),
  ('Tâm âm bất túc - Tâm huyết hư', 'Nội quan', 'Chủ huyệt trị âm huyết hao tổn'),
  ('Tâm âm bất túc - Tâm huyết hư', 'Thần môn', 'Tả hư nhiệt Tâm, an thần định chí'),
  ('Tâm âm bất túc - Tâm huyết hư', 'Chí dương', 'Tả hoả ở Phế, Đảm, giữ chân âm'),
  ('Tâm âm bất túc - Tâm huyết hư', 'Phế du', 'Tả hoả ở Phế, Đảm, giữ chân âm'),
  ('Tâm âm bất túc - Tâm huyết hư', 'Can du', 'Mạnh sinh huyết, tàng huyết Can Tỳ'),
  ('Tâm âm bất túc - Tâm huyết hư', 'Tỳ du', 'Mạnh sinh huyết, tàng huyết Can Tỳ'),
  ('Tâm âm bất túc - Tâm huyết hư', 'Huyết linh', 'Mạnh sinh huyết, tàng huyết Can Tỳ'),
  ('Tâm huyết ứ trệ', 'Thiếu xung', 'Chích nặn máu, giải co thắt cơ tim, mạch vành'),
  ('Tâm huyết ứ trệ', 'Đảm du', 'Khứ ứ kết ở Đảm, hành khí hành huyết'),
  ('Tâm huyết ứ trệ', 'Dương cương', 'Khứ ứ kết ở Đảm, hành khí hành huyết'),
  ('Tâm huyết ứ trệ', 'Thần môn', 'Thông kinh hoạt lạc'),
  ('Tâm huyết ứ trệ', 'Chi chính', 'Thông kinh hoạt lạc'),
  ('Tâm huyết ứ trệ', 'Can du', 'Tả Can hoả, dứt nguồn sinh phong'),
  ('Tâm huyết ứ trệ', 'Thái xung', 'Tả Can hoả, dứt nguồn sinh phong'),
  ('Đàm hoả nội nhiễu (đàm hoả nhiễu tâm)', 'Tâm du', 'Tả nhiệt ở Tâm làm thần chí tán loạn'),
  ('Đàm hoả nội nhiễu (đàm hoả nhiễu tâm)', 'Thần đạo', 'Tả nhiệt ở Tâm làm thần chí tán loạn'),
  ('Đàm hoả nội nhiễu (đàm hoả nhiễu tâm)', 'Thiên tỉnh', 'Tả nhiệt ở Tâm làm thần chí tán loạn'),
  ('Đàm hoả nội nhiễu (đàm hoả nhiễu tâm)', 'Khúc trì', 'Giải phong tả nhiệt ở gân bắp trị thao cuồng'),
  ('Đàm hoả nội nhiễu (đàm hoả nhiễu tâm)', 'Túc tam lý', 'Giải phong tả nhiệt ở gân bắp trị thao cuồng'),
  ('Đàm mê tâm khiếu (Đàm trở tâm bào)', 'Nhĩ tiêm', 'Giảm urê máu, chống hôn mê sâu'),
  ('Đàm mê tâm khiếu (Đàm trở tâm bào)', 'Nhân trung', 'Khai khiếu tinh thần, cấp cứu choáng ngất'),
  ('Đàm mê tâm khiếu (Đàm trở tâm bào)', 'Bách hội', 'Khai khiếu tinh thần, cấp cứu choáng ngất'),
  ('Đàm mê tâm khiếu (Đàm trở tâm bào)', 'Dũng tuyền', 'Khai khiếu tinh thần, cấp cứu choáng ngất'),
  ('Đàm mê tâm khiếu (Đàm trở tâm bào)', 'Trung xung', 'Tỉnh huyệt kinh Tâm bào, giải tà khí ở Tâm'),
  ('Tâm hoả thượng viên (Tâm hoả cang thịnh)', 'Thần môn', 'Trị Tâm hoả cang thịnh gây nứt, sưng lưỡi'),
  ('Tâm hoả thượng viên (Tâm hoả cang thịnh)', 'Nội đình', 'Trị Tâm hoả cang thịnh gây nứt, sưng lưỡi'),
  ('Tâm hoả thượng viên (Tâm hoả cang thịnh)', 'Kim tân', 'Chữa lưỡi sưng đau'),
  ('Tâm hoả thượng viên (Tâm hoả cang thịnh)', 'Ngọc dịch', 'Chữa lưỡi sưng đau'),
  ('Tiểu trường thực nhiệt (Tâm di nhiệt sang tiểu trường)', 'Thiếu trạch', 'Tỉnh huyệt, trừ nhiệt kinh Tiểu trường và Bàng quang'),
  ('Tiểu trường thực nhiệt (Tâm di nhiệt sang tiểu trường)', 'Liệt khuyết', 'Trị nhiệt làm khí không hoá, đái máu, đái buốt'),
  ('Tiểu trường thực nhiệt (Tâm di nhiệt sang tiểu trường)', 'Côn lôn', 'Trị nhiệt làm khí không hoá, đái máu, đái buốt'),
  ('Tiểu trường khí thống', 'Đại đôn', 'Tả mộc khí Can kinh, trị đau co thắt bụng dưới'),
  ('Tiểu trường khí thống', 'Khí hải', 'Trị cơn đau quặn dọc cơ thẳng bụng'),
  ('Tiểu trường khí thống', 'Thái xung', 'Trị cơn đau quặn dọc cơ thẳng bụng'),
  ('Tiểu trường khí thống', 'Nội đình', 'Trị cơn đau quặn dọc cơ thẳng bụng'),
  ('Can uất (can khí uất kết, can khí bất thư) (can khí không thả lỏng):', 'Khố phòng', 'Khai khí uất ở lồng ngực'),
  ('Can uất (can khí uất kết, can khí bất thư) (can khí không thả lỏng):', 'Nội quan', 'Sơ can lý khí'),
  ('Can uất (can khí uất kết, can khí bất thư) (can khí không thả lỏng):', 'Thái xung', 'Sơ can lý khí'),
  ('Can uất (can khí uất kết, can khí bất thư) (can khí không thả lỏng):', 'Chi câu', 'Chữa đau vỏ lồng ngực'),
  ('Can uất (can khí uất kết, can khí bất thư) (can khí không thả lỏng):', 'Túc tam lý', 'Dẫn hoả đi xuống'),
  ('Can uất (can khí uất kết, can khí bất thư) (can khí không thả lỏng):', 'Tỳ du', 'Bổ Can Tỳ khí, phá gốc bĩ, chữa gan lách sưng to'),
  ('Can uất (can khí uất kết, can khí bất thư) (can khí không thả lỏng):', 'Bĩ căn', 'Bổ Can Tỳ khí, phá gốc bĩ, chữa gan lách sưng to'),
  ('Can uất (can khí uất kết, can khí bất thư) (can khí không thả lỏng):', 'Chương môn', 'Bổ Can Tỳ khí, phá gốc bĩ, chữa gan lách sưng to'),
  ('Can uất (can khí uất kết, can khí bất thư) (can khí không thả lỏng):', 'Công tôn', 'Bổ Can Tỳ khí, phá gốc bĩ, chữa gan lách sưng to'),
  ('Trúng phong (Kẹt động mạch não)', 'Huyền ly', 'Hoãn giải động mạch não'),
  ('Trúng phong (Kẹt động mạch não)', 'Túc lâm khấp', 'Hoãn giải động mạch não'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Phong trì', 'Chữa cao huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Khúc trì', 'Chữa cao huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Dương lăng tuyền', 'Chữa cao huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Hành gian', 'Chữa cao huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Can', 'Nhĩ châm hạ huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Thận', 'Nhĩ châm hạ huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Rãnh giáng áp', 'Nhĩ châm hạ huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Túc tam lý', 'Chữa cao huyết áp; thuỷ châm'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Hợp cốc', 'Chữa cao huyết áp; thuỷ châm'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Nhân nghinh', 'Chữa cao huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Thái xung', 'Chữa cao huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Nội quan', 'Chữa cao huyết áp; thuỷ châm'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Tam âm giao', 'Thuỷ châm luân lưu chi trên-dưới'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Huyết áp điểm', 'Chữa cao huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Kiên nội lăng', 'Chữa cao huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'An miên 1', 'Chữa cao huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'An miên 2', 'Chữa cao huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Tiền hậu ẩn châu', 'Chữa cao huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Ấn đường', 'Chữa cao huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Tĩnh mạch sau tai', 'Chữa cao huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Tân khúc trì', 'Chữa cao huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Lạc linh ngũ', 'Chữa cao huyết áp'),
  ('Huyễn vận (Sung huyết não do huyết áp cao)', 'Nham trì', 'Chữa cao huyết áp'),
  ('Bệnh đốt sống cổ', 'Thừa tương', 'Cổ gáy cứng đau, đau đầu cứng gáy'),
  ('Bệnh đốt sống cổ', 'Phong phủ', 'Cổ gáy cứng đau, đau đầu cứng gáy'),
  ('Bệnh đốt sống cổ', 'Thiên dũ', 'Cổ gáy không xoay được'),
  ('Bệnh đốt sống cổ', 'Hậu khê', 'Tả, chữa đầu không quay trái phải'),
  ('Bệnh đốt sống cổ', 'Thiên trụ', 'Sái cổ, cứng gáy'),
  ('Bệnh đốt sống cổ', 'Lạc chẩm', 'Cứng gáy, sái cổ'),
  ('Bệnh đốt sống cổ', 'Phong trì', 'Sái cổ, căng gáy đầu'),
  ('Bệnh đốt sống cổ', 'Ôn lưu', 'Bị lạnh mà cứng cổ gáy'),
  ('Bệnh đốt sống cổ', 'Kỳ môn', 'Bị lạnh mà cứng cổ gáy'),
  ('Bệnh đốt sống cổ', 'Liệt khuyết', 'Đau gáy đầu'),
  ('Bệnh đốt sống cổ', 'Tân thiết', 'Đầu gáy cứng đau'),
  ('Bệnh đốt sống cổ', 'Giáp tích', 'Bệnh vùng cổ gáy'),
  ('Bệnh đốt sống cổ', 'Cảnh trung', 'Gáy cổ cứng đau'),
  ('Bệnh đốt sống cổ', 'Ngũ hổ', 'Đau gáy cổ'),
  ('Bệnh đốt sống cổ', 'Dung hậu', 'Đau gáy cổ'),
  ('Bệnh đốt sống cổ', 'Bát tà', 'Đau gáy cổ'),
  ('Bệnh đốt sống cổ', 'Thượng bát tà', 'Đau gáy cổ'),
  ('Bệnh đốt sống cổ', 'Tân thức', 'Cứng gáy'),
  ('Bệnh đốt sống cổ', 'Sùng cốt', 'Cứng gáy'),
  ('Bệnh đốt sống cổ', 'Lạc cảnh', 'Sái cổ'),
  ('Bệnh đốt sống cổ', 'Bách lao', 'Sái cổ'),
  ('Bệnh đốt sống cổ', 'Định suyễn', 'Sái cổ'),
  ('Bệnh đốt sống cổ', 'Lạc linh ngũ', 'Sái cổ'),
  ('Bệnh đốt sống cổ', 'Hợp cốc', 'Sái cổ'),
  ('Bệnh đốt sống cổ', 'Kinh cốt', 'Tả, chữa đầu không cúi ngửa được'),
  ('Bệnh đốt sống cổ', 'Uỷ trung', 'Bổ, chữa đầu không cúi ngửa được'),
  ('Bệnh đốt sống cổ', 'Đại trữ', 'Tả, chữa đầu không cúi ngửa được'),
  ('Bệnh đốt sống cổ', 'Phong môn', 'Tả, chữa đầu không cúi ngửa được'),
  ('Bệnh đốt sống cổ', 'Kiên ngoại du', 'Tả, chữa đầu không quay trái phải'),
  ('Bệnh đốt sống cổ', 'Hạng cường', 'Thêm khi bất kỳ kinh nào bị bệnh'),
  ('Bệnh đốt sống cổ', 'Giáp tích 1-7', 'Bệnh vùng cổ gáy'),
  ('Yêu thống (bệnh đau lưng)', 'Mệnh môn', 'Đau lưng, thận hư'),
  ('Yêu thống (bệnh đau lưng)', 'Áp thống điểm', 'Điểm ấn đau, bong gân thắt lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Thận du', 'Đau lưng, thận hư'),
  ('Yêu thống (bệnh đau lưng)', 'Uỷ trung', 'Đau lưng (huyệt chính)'),
  ('Yêu thống (bệnh đau lưng)', 'Thận tích', 'Đau lưng, viêm đốt sống'),
  ('Yêu thống (bệnh đau lưng)', 'Yêu dương quan', 'Phong thấp hàn, viêm cột sống'),
  ('Yêu thống (bệnh đau lưng)', 'Ân môn', 'Đau lưng không cúi ngửa được'),
  ('Yêu thống (bệnh đau lưng)', 'A thị huyệt', 'Phong thấp hàn đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Thái khê', 'Thận hư đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Yêu nhãn', 'Cơ lưng lao tổn, đau thắt lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Nhân trung', 'Bong gân cấp, đau sát thắt lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Ngân giao', 'Đau sát thắt lưng, bong gân cấp'),
  ('Yêu thống (bệnh đau lưng)', 'Yêu thoái điểm', 'Châm bàn tay chữa đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Giao cảm', 'Nhĩ châm đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Thần môn', 'Nhĩ châm đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Yêu', 'Nhĩ châm đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Thận', 'Nhĩ châm đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Đại trường du', 'Đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Dưỡng lão', 'Đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Yêu du', 'Đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Kinh môn', 'Đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Hành gian', 'Đau lưng, khó động đậy'),
  ('Yêu thống (bệnh đau lưng)', 'Phong thị', 'Đau lưng khó động đậy'),
  ('Yêu thống (bệnh đau lưng)', 'Phục lưu', 'Lưng trên dưới đau'),
  ('Yêu thống (bệnh đau lưng)', 'Côn lôn', 'Lưng trên dưới đau'),
  ('Yêu thống (bệnh đau lưng)', 'Uỷ dương', 'Đau thắt lưng, không cúi ngửa'),
  ('Yêu thống (bệnh đau lưng)', 'Cách quan', 'Cột sống cứng cấp tính'),
  ('Yêu thống (bệnh đau lưng)', 'Thuỷ phân', 'Cột sống cứng cấp tính'),
  ('Yêu thống (bệnh đau lưng)', 'Á môn', 'Cột sống gãy ngược, thoát vị đĩa đệm'),
  ('Yêu thống (bệnh đau lưng)', 'Phong phủ', 'Cột sống gãy ngược lại'),
  ('Yêu thống (bệnh đau lưng)', 'Đại chùy', 'Viêm cột sống phong thấp, còng gù lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Thân trụ', 'Viêm cột sống do phong thấp'),
  ('Yêu thống (bệnh đau lưng)', 'Chí dương', 'Viêm cột sống do phong thấp'),
  ('Yêu thống (bệnh đau lưng)', 'Cân súc', 'Viêm cột sống do phong thấp'),
  ('Yêu thống (bệnh đau lưng)', 'Tiểu trường du', 'Viêm cột sống do phong thấp'),
  ('Yêu thống (bệnh đau lưng)', 'Tỳ du', 'Viêm cột sống do phong thấp'),
  ('Yêu thống (bệnh đau lưng)', 'Đại trữ', 'Cột sống cứng cấp; viêm cột sống'),
  ('Yêu thống (bệnh đau lưng)', 'Bạch hoàn du', 'Lưng trên liền lưng dưới đau'),
  ('Yêu thống (bệnh đau lưng)', 'Chí thất', 'Tổn thương phần mềm thắt lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Quan nguyên', 'Tổn thương phần mềm; còng gù lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Quan nguyên du', 'Phong lao đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Bàng quang du', 'Phong lao đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Thập thất chuỳ hạ', 'Đau thắt lưng và xương cùng'),
  ('Yêu thống (bệnh đau lưng)', 'Trật biên', 'Đau lưng đùi, xương cùng'),
  ('Yêu thống (bệnh đau lưng)', 'Đĩnh yêu', 'Lưng đùi đau, đau lưng mạn tính'),
  ('Yêu thống (bệnh đau lưng)', 'Thừa phù', 'Lưng đùi đau, đau khớp hông'),
  ('Yêu thống (bệnh đau lưng)', 'Toạ cốt', 'Lưng đùi đau'),
  ('Yêu thống (bệnh đau lưng)', 'Dương lăng tuyền', 'Lưng đùi đau, đau khớp hông'),
  ('Yêu thống (bệnh đau lưng)', 'Túc tam lý', 'Còng gù lưng (cứu)'),
  ('Yêu thống (bệnh đau lưng)', 'Đại hoành', 'Còng gù do mềm xương'),
  ('Yêu thống (bệnh đau lưng)', 'Phong trì', 'Lưng còng khom'),
  ('Yêu thống (bệnh đau lưng)', 'Phế du', 'Lưng còng khom'),
  ('Yêu thống (bệnh đau lưng)', 'Hậu khê', 'Bong gân cấp vùng lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Giáp tích', 'Bệnh vùng thắt lưng, xương sống'),
  ('Yêu thống (bệnh đau lưng)', 'Thành cốt', 'Đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Hạ côn lôn', 'Đau lưng, đau nhức mình mẩy'),
  ('Yêu thống (bệnh đau lưng)', 'Trị chuyển cân', 'Đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Tuyển sinh túc', 'Đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Hoàn trung', 'Đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Hạ cực du', 'Đau lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Phế nhiệt huyệt', 'Đau lưng trên, đau thắt lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Tích tam huyệt', 'Viêm cột sống, bệnh tuỷ sống'),
  ('Yêu thống (bệnh đau lưng)', 'Âm hạ', 'Đau buốt lưng trên dưới'),
  ('Yêu thống (bệnh đau lưng)', 'Khê thượng', 'Đau lưng mạn tính'),
  ('Yêu thống (bệnh đau lưng)', 'Tiếp cốt', 'Đau thắt lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Yêu nghi', 'Tổn thương phần mềm ở lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Trung không', 'Tổn thương phần mềm ở lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Nữu thương', 'Bong gân cấp tính thắt lưng'),
  ('Yêu thống (bệnh đau lưng)', 'Khách tân trung', 'Đau lưng đùi'),
  ('Yêu thống (bệnh đau lưng)', 'Ân thượng', 'Đau lưng đùi'),
  ('Yêu thống (bệnh đau lưng)', 'Ngoại âm liêm', 'Thắt lưng và đùi đau'),
  ('Yêu thống (bệnh đau lưng)', 'Tích phùng', 'Viêm cột sống, viêm tuỷ sống'),
  ('Yêu thống (bệnh đau lưng)', 'Yêu thống 1', 'Thắt lưng ngoại thương'),
  ('Yêu thống (bệnh đau lưng)', 'Yêu thống 3', 'Thắt lưng ngoại thương'),
  ('Yêu thống (bệnh đau lưng)', 'Ngoại khoả tiêm', 'Đau nhức mình mẩy (thống phong)'),
  ('Yêu thống (bệnh đau lưng)', 'Thượng nhĩ căn', 'Xơ hoá từng mảng tuỷ sống'),
  ('Yêu thống (bệnh đau lưng)', 'Ngọc điều', 'Đau xương cùng'),
  ('Yêu thống (bệnh đau lưng)', 'Yêu căn', 'Bệnh khớp cùng chậu'),
  ('Can dương thượng cang (can dương cang thịnh, âm hư can vượng)', 'Bách hội', 'Chữa đau đầu do can hoả'),
  ('Can dương thượng cang (can dương cang thịnh, âm hư can vượng)', 'Hành gian', 'Chữa đau đầu do can hoả'),
  ('Can dương thượng cang (can dương cang thịnh, âm hư can vượng)', 'Kiên ngung', 'Làm giảm huyết áp'),
  ('Can dương thượng cang (can dương cang thịnh, âm hư can vượng)', 'Hợp cốc', 'Trấn kinh, chống co quắp co giật'),
  ('Can dương thượng cang (can dương cang thịnh, âm hư can vượng)', 'Thái xung', 'Trấn kinh, chống co quắp co giật'),
  ('Can dương thượng cang (can dương cang thịnh, âm hư can vượng)', 'Can nhiệt huyệt', 'Tả Can nhiệt'),
  ('Can dương thượng cang (can dương cang thịnh, âm hư can vượng)', 'Túc tam lý', 'Dẫn hoả đi xuống'),
  ('Can dương thượng cang (can dương cang thịnh, âm hư can vượng)', 'Tam âm giao', 'Tư thận âm, chế Can hoả'),
  ('Can dương thượng cang (can dương cang thịnh, âm hư can vượng)', 'Phong trì', 'Chữa liệt nửa người'),
  ('Can dương thượng cang (can dương cang thịnh, âm hư can vượng)', 'Khúc trì', 'Chữa liệt nửa người'),
  ('Can dương thượng cang (can dương cang thịnh, âm hư can vượng)', 'Dương lăng tuyền', 'Chữa liệt nửa người'),
  ('Can âm bất túc', 'Cách du', 'Bổ âm'),
  ('Can âm bất túc', 'Đảm du', 'Bổ âm'),
  ('Can âm bất túc', 'Nội quan', 'Bổ tâm huyết'),
  ('Can âm bất túc', 'Túc tam lý', 'Bổ Tỳ, tăng vận hoá'),
  ('Can âm bất túc', 'Tỳ du', 'Bổ Tỳ, tăng vận hoá'),
  ('Can âm bất túc', 'Thận du', 'Bổ thận âm'),
  ('Can âm bất túc', 'Tam âm giao', 'Bổ thận âm'),
  ('Can âm bất túc', 'Dương lăng tuyền', 'Làm gân cơ chi dưới vững chắc'),
  ('Đảm nhiệt (can đảm thấp nhiệt)', 'Não hộ', 'Trị Đảm nhiệt'),
  ('Đảm nhiệt (can đảm thấp nhiệt)', 'Đảm du', 'Trị Đảm nhiệt'),
  ('Đảm nhiệt (can đảm thấp nhiệt)', 'Dương cương', 'Trị Đảm nhiệt'),
  ('Đảm nhiệt (can đảm thấp nhiệt)', 'Chí dương', 'Tả hoả ở Can Đảm, liên sườn'),
  ('Đảm nhiệt (can đảm thấp nhiệt)', 'Chi câu', 'Chữa đau vỏ lồng ngực'),
  ('Đảm nhiệt (can đảm thấp nhiệt)', 'Nội quan', 'Điều hoà công năng nội tạng'),
  ('Tỳ dương hư (Tỳ dương bất chấn, tỳ vị hư hàn)', 'Thần môn', 'Tăng hấp thụ dinh dưỡng'),
  ('Tỳ dương hư (Tỳ dương bất chấn, tỳ vị hư hàn)', 'Chi chính', 'Tăng hấp thụ dinh dưỡng'),
  ('Tỳ dương hư (Tỳ dương bất chấn, tỳ vị hư hàn)', 'Tuỵ du', 'Tăng công năng tuyến tuỵ'),
  ('Tỳ dương hư (Tỳ dương bất chấn, tỳ vị hư hàn)', 'Tỳ du', 'Tăng công năng tuyến tuỵ'),
  ('Tỳ dương hư (Tỳ dương bất chấn, tỳ vị hư hàn)', 'Ý xá', 'Tăng công năng tuyến tuỵ'),
  ('Tỳ dương hư (Tỳ dương bất chấn, tỳ vị hư hàn)', 'Trung quản', 'Bổ tỳ vị'),
  ('Tỳ dương hư (Tỳ dương bất chấn, tỳ vị hư hàn)', 'Nội quan', 'Bổ tỳ vị'),
  ('Tỳ dương hư (Tỳ dương bất chấn, tỳ vị hư hàn)', 'Túc tam lý', 'Bổ tỳ vị'),
  ('Tỳ vị khí hư (tỳ vị hư nhược, trung khí bất túc)', 'Tỳ du', 'Bổ công năng tỳ vị'),
  ('Tỳ vị khí hư (tỳ vị hư nhược, trung khí bất túc)', 'Vị du', 'Bổ công năng tỳ vị'),
  ('Tỳ vị khí hư (tỳ vị hư nhược, trung khí bất túc)', 'Trung quản', 'Bổ công năng tỳ vị'),
  ('Tỳ vị khí hư (tỳ vị hư nhược, trung khí bất túc)', 'Quan nguyên', 'Đại bổ nguyên khí'),
  ('Tỳ vị khí hư (tỳ vị hư nhược, trung khí bất túc)', 'Tam âm giao', 'Bồi bổ âm huyết'),
  ('Tỳ vị khí hư (tỳ vị hư nhược, trung khí bất túc)', 'Nội quan', 'Bồi bổ âm huyết'),
  ('Tỳ vị khí hư (tỳ vị hư nhược, trung khí bất túc)', 'Đại chùy', 'Hạ sốt'),
  ('Tỳ vị khí hư (tỳ vị hư nhược, trung khí bất túc)', 'Khúc trì', 'Hạ sốt'),
  ('Tỳ vị khí hư (tỳ vị hư nhược, trung khí bất túc)', 'Hợp cốc', 'Hạ sốt'),
  ('Tỳ vị khí hư (tỳ vị hư nhược, trung khí bất túc)', 'Ẩn bạch', 'Cầm máu'),
  ('Tỳ vị khí hư (tỳ vị hư nhược, trung khí bất túc)', 'Đại đôn', 'Cầm máu'),
  ('Tỳ vị thấp khốn (Tỳ hư thấp khốn, thấp khôn tỳ dương)', 'Tỳ du', 'Bổ tỳ vị, vận hoá thấp trọc'),
  ('Tỳ vị thấp khốn (Tỳ hư thấp khốn, thấp khôn tỳ dương)', 'Vị du', 'Bổ tỳ vị, vận hoá thấp trọc'),
  ('Tỳ vị thấp khốn (Tỳ hư thấp khốn, thấp khôn tỳ dương)', 'Đảm du', 'Trừ hàn khí ở Đảm'),
  ('Tỳ vị thấp khốn (Tỳ hư thấp khốn, thấp khôn tỳ dương)', 'Hợp cốc', 'Vận Tỳ hoá thấp ở đầu mặt'),
  ('Tỳ vị thấp khốn (Tỳ hư thấp khốn, thấp khôn tỳ dương)', 'Túc tam lý', 'Vận Tỳ hoá thấp ở đầu mặt'),
  ('Tỳ vị thấp khốn (Tỳ hư thấp khốn, thấp khôn tỳ dương)', 'Đại chung', 'Chữa ngại nói ham nằm do thấp khốn'),
  ('Thấp nhiệt nội uẩn (Tỳ uẩn thấp nhiệt)', 'Não hộ', 'Trị viêm túi mật, tắc ống mật'),
  ('Thấp nhiệt nội uẩn (Tỳ uẩn thấp nhiệt)', 'Đảm du', 'Trị viêm túi mật, tắc ống mật'),
  ('Thấp nhiệt nội uẩn (Tỳ uẩn thấp nhiệt)', 'Dương cương', 'Trị viêm túi mật, tắc ống mật'),
  ('Thấp nhiệt nội uẩn (Tỳ uẩn thấp nhiệt)', 'Túc tam lý', 'Trị viêm gan cấp mạn'),
  ('Thấp nhiệt nội uẩn (Tỳ uẩn thấp nhiệt)', 'Thái xung', 'Trị viêm gan cấp mạn'),
  ('Tâm tỳ lường hư', 'Cách du', 'Tứ hoa, bồi bổ cả khí và huyết'),
  ('Tâm tỳ lường hư', 'Tâm du', 'Trị chứng hay quên'),
  ('Tâm tỳ lường hư', 'Đảm du', 'Tứ hoa, bồi bổ cả khí và huyết'),
  ('Tâm tỳ lường hư', 'Thần môn', 'Bổ Tâm, biểu lý với Tiểu trường'),
  ('Tâm tỳ lường hư', 'Chi chính', 'Biểu lý Tiểu trường, giúp Tâm khoẻ'),
  ('Tâm tỳ lường hư', 'Tỳ du', 'Bổ trực tiếp vào Tỳ Vị'),
  ('Tâm tỳ lường hư', 'Vị du', 'Bổ trực tiếp vào Tỳ Vị'),
  ('Tâm tỳ lường hư', 'Túc tam lý', 'Bổ trực tiếp vào Tỳ Vị'),
  ('Tâm tỳ lường hư', 'Thiếu dương', 'Trị chứng hay quên'),
  ('Tâm tỳ lường hư', 'Dũng tuyền', 'Trị chứng hay quên'),
  ('Tỳ thận dương hư', 'Tỳ du', 'Trực tiếp bổ thận'),
  ('Tỳ thận dương hư', 'Thận du', 'Trực tiếp bổ thận'),
  ('Tỳ thận dương hư', 'Bách hội', 'Bổ thận dương, cầm ỉa chảy'),
  ('Tỳ thận dương hư', 'Thái khê', 'Bổ thận dương, ấm ngũ tạng'),
  ('Tỳ thận dương hư', 'Túc tam lý', 'Tăng cường vận hoá của Tỳ'),
  ('Tỳ thận dương hư', 'Cách du', 'Bổ dưỡng khí huyết'),
  ('Tỳ thận dương hư', 'Đảm du', 'Bổ dưỡng khí huyết'),
  ('Tỳ thận dương hư', 'Côn lôn', 'Cứu ngăn cơn suyễn, ấm lưng'),
  ('Tỳ thận dương hư', 'Đại chung', 'Trị chứng ngại nói, ham nằm'),
  ('Tỳ thận dương hư', 'Thông lý', 'Trị chứng ngại nói, ham nằm'),
  ('Vị hoả thịnh (tà nhiệt nhiễu vị, vị hoả tích thịnh)', 'Đầu duy', 'Tả nhiệt vùng trước trán'),
  ('Vị hoả thịnh (tà nhiệt nhiễu vị, vị hoả tích thịnh)', 'Dương bạch', 'Tả nhiệt vùng trước trán'),
  ('Vị hoả thịnh (tà nhiệt nhiễu vị, vị hoả tích thịnh)', 'Hợp cốc', 'Tả nhiệt vùng trước trán'),
  ('Vị hoả thịnh (tà nhiệt nhiễu vị, vị hoả tích thịnh)', 'Giải khê', 'Tả nhiệt vùng trước trán'),
  ('Vị hoả thịnh (tà nhiệt nhiễu vị, vị hoả tích thịnh)', 'Khúc trì', 'Hạ nhiệt, dẫn hoả xuống, dứt phiền thao'),
  ('Vị hoả thịnh (tà nhiệt nhiễu vị, vị hoả tích thịnh)', 'Túc tam lý', 'Hạ nhiệt, dẫn hoả xuống, dứt phiền thao'),
  ('Vị hoả thịnh (tà nhiệt nhiễu vị, vị hoả tích thịnh)', 'Đại lăng', 'Trị xuất huyết dạ dày, thổ huyết'),
  ('Vị hoả thịnh (tà nhiệt nhiễu vị, vị hoả tích thịnh)', 'Khích môn', 'Trị xuất huyết dạ dày, thổ huyết'),
  ('Vị hoả thịnh (tà nhiệt nhiễu vị, vị hoả tích thịnh)', 'Thượng tinh', 'Cầm chảy máu mũi (nục huyết)'),
  ('Vị hoả thịnh (tà nhiệt nhiễu vị, vị hoả tích thịnh)', 'Tố liêu', 'Cầm chảy máu mũi (nục huyết)'),
  ('Vị hoả thịnh (tà nhiệt nhiễu vị, vị hoả tích thịnh)', 'Đoài đoan', 'Chữa vòm miệng, lợi răng sưng đau'),
  ('Vị hoả thịnh (tà nhiệt nhiễu vị, vị hoả tích thịnh)', 'Ngân giao', 'Chữa vòm miệng, lợi răng sưng đau'),
  ('Vị hoả thịnh (tà nhiệt nhiễu vị, vị hoả tích thịnh)', 'Thừa tương', 'Chữa vòm miệng, lợi răng sưng đau'),
  ('Vị âm hư', 'Đầu duy', 'Tả nhiệt vùng trước trán'),
  ('Vị âm hư', 'Dương bạch', 'Tả nhiệt vùng trước trán'),
  ('Vị âm hư', 'Hợp cốc', 'Tả nhiệt vùng trước trán'),
  ('Vị âm hư', 'Giải khê', 'Tả nhiệt vùng trước trán'),
  ('Vị âm hư', 'Khúc trì', 'Hạ nhiệt, dẫn hoả xuống, dứt phiền thao'),
  ('Vị âm hư', 'Túc tam lý', 'Hạ nhiệt, dẫn hoả xuống, dứt phiền thao'),
  ('Vị âm hư', 'Nội quan', 'Bổ âm, trừ hư hoả'),
  ('Vị âm hư', 'Tam âm giao', 'Bổ âm, trừ hư hoả'),
  ('Can vị bất hoà (can khí phạm vị)', 'Kỳ môn', 'Trị riêng chứng Can'),
  ('Can vị bất hoà (can khí phạm vị)', 'Thái xung', 'Trị riêng chứng Can'),
  ('Can vị bất hoà (can khí phạm vị)', 'Trung quản', 'Phương huyệt truyền thống trị đau dạ dày'),
  ('Can vị bất hoà (can khí phạm vị)', 'Lương môn', 'Cầu nối, trị chung vùng bụng trên'),
  ('Can vị bất hoà (can khí phạm vị)', 'Nội quan', 'Phương huyệt truyền thống trị đau dạ dày'),
  ('Can vị bất hoà (can khí phạm vị)', 'Túc tam lý', 'Phương huyệt truyền thống trị đau dạ dày'),
  ('Can vị bất hoà (can khí phạm vị)', 'Đại lăng', 'Tả khi nôn ra máu'),
  ('Can vị bất hoà (can khí phạm vị)', 'Khích môn', 'Tả khi nôn ra máu'),
  ('Tỳ vị hư hàn', 'Ẩn bạch', 'Trị ỉa ra phân đen'),
  ('Đàm trọc trở phế ( đàm ẩm phạm phế)', 'Lệ đoài', 'Đặc trị tiết dịch xoang sau'),
  ('Đàm trọc trở phế ( đàm ẩm phạm phế)', 'Kinh cốt', 'Đặc trị tiết dịch xoang sau'),
  ('Đàm trọc trở phế ( đàm ẩm phạm phế)', 'Hậu khê', 'Đặc trị tiết dịch xoang sau'),
  ('Đàm trọc trở phế ( đàm ẩm phạm phế)', 'Côn lôn', 'Cắt cơn suyễn'),
  ('Đàm trọc trở phế ( đàm ẩm phạm phế)', 'Tân lặc đầu', 'Chữa viêm phế quản có đờm'),
  ('Đàm trọc trở phế ( đàm ẩm phạm phế)', 'Đản trung', 'Chữa viêm phế quản có đờm'),
  ('Đàm trọc trở phế ( đàm ẩm phạm phế)', 'Phong long', 'Chữa viêm phế quản có đờm'),
  ('Đàm trọc trở phế ( đàm ẩm phạm phế)', 'Đại chùy', 'Trị giãn phế quản, đờm có máu'),
  ('Đàm trọc trở phế ( đàm ẩm phạm phế)', 'Trung phủ', 'Trị giãn phế quản, đờm có máu'),
  ('Phế hàn khái suyễn ( phong hàn thúc phế: phế bị gió lạnh làm ho)', 'Phong môn', 'Làm ấm Phế tạng, đuổi hàn tà'),
  ('Phế hàn khái suyễn ( phong hàn thúc phế: phế bị gió lạnh làm ho)', 'Phế du', 'Làm ấm Phế tạng, đuổi hàn tà'),
  ('Phế hàn khái suyễn ( phong hàn thúc phế: phế bị gió lạnh làm ho)', 'Thái khê', 'Nâng sức nóng, giúp Phế khí túc giáng'),
  ('Phế hàn khái suyễn ( phong hàn thúc phế: phế bị gió lạnh làm ho)', 'Côn lôn', 'Làm ấm kinh Bàng quang, cắt cơn hen'),
  ('Phế hàn khái suyễn ( phong hàn thúc phế: phế bị gió lạnh làm ho)', 'Phong long', 'Bổ khí, hoá đàm hàn'),
  ('Phế hàn khái suyễn ( phong hàn thúc phế: phế bị gió lạnh làm ho)', 'Đản trung', 'Bổ khí, hoá đàm hàn'),
  ('Phế nhiệt khái suyễn ( Phổi nóng mà ho hen)', 'Thiếu thương', 'Chích nặn máu hạ nhiệt nhiều tạng'),
  ('Phế nhiệt khái suyễn ( Phổi nóng mà ho hen)', 'Xích trạch', 'Nặn máu hạ nhiệt trường Vị'),
  ('Phế nhiệt khái suyễn ( Phổi nóng mà ho hen)', 'Khổng tối', 'Khích huyệt Phế, trị bệnh cấp tính'),
  ('Phế nhiệt khái suyễn ( Phổi nóng mà ho hen)', 'Phế du', 'Tác dụng gần nhất với phế tạng'),
  ('Phế nhiệt khái suyễn ( Phổi nóng mà ho hen)', 'Phế nhiệt huyệt', 'Tác dụng gần nhất với phế tạng'),
  ('Phế nhiệt khái suyễn ( Phổi nóng mà ho hen)', 'Đại chùy', 'Tả bớt dương khí hữu dư để mát'),
  ('Phế nhiệt khái suyễn ( Phổi nóng mà ho hen)', 'Trung phủ', 'Mộ huyệt Phế, tả tà nhiệt hữu dư'),
  ('Phế nhiệt khái suyễn ( Phổi nóng mà ho hen)', 'Thái xung', 'Tả Can hoả phản khắc Phế kim'),
  ('Phế nhiệt khái suyễn ( Phổi nóng mà ho hen)', 'Túc tam lý', 'Bổ để dẫn hoả đi xuống'),
  ('Phế nhiệt khái suyễn ( Phổi nóng mà ho hen)', 'Dương lăng tuyền', 'Tả nhiệt của đảm'),
  ('Phế khí hư', 'Phế du', 'Cứu ôn bổ phế tạng'),
  ('Phế khí hư', 'Cao hoang du', 'Bổ khí, tăng thúc đẩy Phế khí'),
  ('Phế khí hư', 'Túc tam lý', 'Bổ khí, tăng thúc đẩy Phế khí'),
  ('Phế khí hư', 'Cách du', 'Tứ hoa, bổ phế khí và khí hoá'),
  ('Phế khí hư', 'Đảm du', 'Tứ hoa, bổ phế khí và khí hoá'),
  ('Phế khí hư', 'Tỳ du', 'Khí Tỳ khoẻ hỗ trợ Phế khí'),
  ('Phế khí hư', 'Thận du', 'Khí Thận khoẻ hỗ trợ Phế khí'),
  ('Phế khí hư', 'Quan nguyên', 'Giữ gìn nguyên khí toàn thân'),
  ('Phế khí hư', 'Khí hải', 'Giữ gìn nguyên khí toàn thân'),
  ('Phế khí hư', 'Nội quan', 'Bồi bổ âm huyết, huyết sinh khí'),
  ('Phế âm hư (âm hư táo)', 'Cách du', 'Tứ hoa, bồi bổ khí huyết, chống suy nhược'),
  ('Phế âm hư (âm hư táo)', 'Đảm du', 'Tứ hoa, bồi bổ khí huyết, chống suy nhược'),
  ('Phế âm hư (âm hư táo)', 'Thận du', 'Tư âm giáng hoả'),
  ('Phế âm hư (âm hư táo)', 'Phế du', 'Bổ Phế'),
  ('Phế âm hư (âm hư táo)', 'Can du', 'Tả hư hoả ở Can'),
  ('Phế âm hư (âm hư táo)', 'Thái xung', 'Tả hư hoả ở Can'),
  ('Phế âm hư (âm hư táo)', 'Đại chùy', 'Trị giãn phế quản xuất huyết'),
  ('Phế âm hư (âm hư táo)', 'Trung phủ', 'Trị giãn phế quản xuất huyết'),
  ('Phế âm hư (âm hư táo)', 'Túc tam lý', 'Dẫn hoả xuống, bồi thổ sinh kim'),
  ('Phế âm hư (âm hư táo)', 'Tam âm giao', 'Bổ âm ở Can Tỳ Thận'),
  ('Phế tỳ lưỡng hư', 'Phế du', 'Trực tiếp bổ vào Phế tạng'),
  ('Phế tỳ lưỡng hư', 'Tỳ du', 'Bổ Tỳ để bổ phế, bồi thổ sinh kim'),
  ('Phế tỳ lưỡng hư', 'Cách du', 'Tứ hoa, bổ dưỡng khí huyết toàn thân'),
  ('Phế tỳ lưỡng hư', 'Đảm du', 'Tứ hoa, bổ dưỡng khí huyết toàn thân'),
  ('Phế tỳ lưỡng hư', 'Thần môn', 'Nguyên lạc biểu lý, bổ Tâm khí'),
  ('Phế tỳ lưỡng hư', 'Chi chính', 'Nguyên lạc biểu lý, bổ Tâm khí'),
  ('Phế tỳ lưỡng hư', 'Nội quan', 'Bổ vào âm huyết'),
  ('Phế tỳ lưỡng hư', 'Túc tam lý', 'Bổ Tỳ để bổ phế, bồi thổ sinh kim'),
  ('Phế thận lưỡng hư', 'Cách du', 'Tứ hoa, chữa lao phổi hiệu quả'),
  ('Phế thận lưỡng hư', 'Đảm du', 'Tứ hoa, chữa lao phổi hiệu quả'),
  ('Phế thận lưỡng hư', 'Phế du', 'Bổ Phế âm'),
  ('Phế thận lưỡng hư', 'Thận du', 'Bổ thận âm'),
  ('Phế thận lưỡng hư', 'Can du', 'Tả Can Đảm hoả vượng'),
  ('Phế thận lưỡng hư', 'Chí dương', 'Tả Can Đảm hoả vượng'),
  ('Phế thận lưỡng hư', 'Nội quan', 'Bổ âm huyết'),
  ('Phế thận lưỡng hư', 'Tam âm giao', 'Bổ âm huyết'),
  ('Phế thận lưỡng hư', 'Túc tam lý', 'Dẫn hoả khí đi xuống'),
  ('Phế thận lưỡng hư', 'Hợp cốc', 'Cầm mồ hôi, giữ âm tân'),
  ('Phế thận lưỡng hư', 'Phục lưu', 'Cầm mồ hôi, giữ âm tân'),
  ('Đại trường thấp nhiệt', 'Hợp cốc', 'Nguyên huyệt, hạ nhiệt và khử thấp Đại trường'),
  ('Đại trường thấp nhiệt', 'Ngoại quan', 'Lạc huyệt, khử ngoại tà ở tam tiêu'),
  ('Đại trường thấp nhiệt', 'Túc tam lý', 'Kiện tỳ, hoà vị, hoá thấp'),
  ('Đại trường thấp nhiệt', 'Thượng cự hư', 'Hạ hợp huyệt, trị bệnh Đại trường mạnh nhất'),
  ('Thận âm hư', 'Cách du', 'Tứ hoa liệu pháp chữa chứng âm hư'),
  ('Thận âm hư', 'Đảm du', 'Tứ hoa liệu pháp chữa chứng âm hư'),
  ('Thận âm hư', 'Thái dương', 'Chữa đau đầu do thần kinh suy nhược'),
  ('Thận âm hư', 'Hợp cốc', 'Chữa đau đầu do thần kinh suy nhược'),
  ('Thận âm hư', 'Thận du', 'Bổ thận, chữa đau lưng, di tinh'),
  ('Thận âm hư', 'Nội quan', 'Bổ âm huyết'),
  ('Thận âm hư', 'Túc tam lý', 'Bổ âm huyết'),
  ('Thận âm hư', 'Tam âm giao', 'Bổ âm huyết'),
  ('Thận âm hư', 'Bách hội', 'Trừ đau đầu, ù tai hoa mắt do Thận âm hư'),
  ('Thận âm hư', 'Thông thiên', 'Trừ đau đầu, ù tai hoa mắt do Thận âm hư'),
  ('Thận âm hư', 'Dũng tuyền', 'Trừ đau đầu, ù tai hoa mắt do Thận âm hư'),
  ('Thận dương hư (thận dương bất chấn)', 'Bách hội', 'Trị choáng tiền đình, phân lỏng do Thận dương hư'),
  ('Thận dương hư (thận dương bất chấn)', 'Thái khê', 'Trị choáng tiền đình, phân lỏng do Thận dương hư'),
  ('Thận dương hư (thận dương bất chấn)', 'Côn lôn', 'Nâng thân nhiệt, cắt cơn hen suyễn'),
  ('Thận dương hư (thận dương bất chấn)', 'Phế du', 'Tăng công năng Phế, Đảm, tăng dương khí toàn thân'),
  ('Thận dương hư (thận dương bất chấn)', 'Đảm du', 'Tăng công năng Phế, Đảm, tăng dương khí toàn thân'),
  ('Thận dương hư (thận dương bất chấn)', 'Tỳ du', 'Bổ tỳ thận, ấm lưng, chữa lưng gối mỏi đau'),
  ('Thận dương hư (thận dương bất chấn)', 'Thận du', 'Bổ tỳ thận, ấm lưng, chữa lưng gối mỏi đau'),
  ('Thận dương hư (thận dương bất chấn)', 'Bàng quang du', 'Bổ tỳ thận, ấm lưng, chữa lưng gối mỏi đau'),
  ('Thận dương hư (thận dương bất chấn)', 'Liệt khuyết', 'Trị đái không bình thường do khí hoá'),
  ('Thận dương hư (thận dương bất chấn)', 'Quan nguyên', 'Đại bổ nguyên khí, khí dương'),
  ('Thận dương hư (thận dương bất chấn)', 'Khí hải', 'Trị liệt dương'),
  ('Thận dương hư (thận dương bất chấn)', 'Quy lai', 'Trị liệt dương'),
  ('Thận dương hư (thận dương bất chấn)', 'Tam âm giao', 'Trị liệt dương'),
  ('Thận dương hư (thận dương bất chấn)', 'Đốc du', 'Dùng thêm để tăng hiệu quả'),
  ('Thận dương hư (thận dương bất chấn)', 'Hạ liêm', 'Dùng thêm để tăng hiệu quả'),
  ('Thận âm dương lưỡng hư', 'Tâm du', 'Bồi bổ âm huyết, âm tinh'),
  ('Thận âm dương lưỡng hư', 'Cách du', 'Bồi bổ âm huyết, âm tinh'),
  ('Thận âm dương lưỡng hư', 'Nội quan', 'Bồi bổ âm huyết, âm tinh'),
  ('Thận âm dương lưỡng hư', 'Túc tam lý', 'Bồi bổ âm huyết, âm tinh'),
  ('Tâm thận bất giao', 'Thần môn', 'Bổ tâm âm, chữa hồi hộp, mạch nhanh'),
  ('Tâm thận bất giao', 'Nội quan', 'Bổ tâm âm, chữa hồi hộp, mạch nhanh'),
  ('Tâm thận bất giao', 'Tam âm giao', 'Bổ Thận âm, an thần dễ ngủ'),
  ('Tâm thận bất giao', 'Thiếu dương', 'Điều hoà nhịp thở, ổn định nhịp tim'),
  ('Tâm thận bất giao', 'Tâm du', 'Tăng tâm lực, trí nhớ'),
  ('Tâm thận bất giao', 'Dũng tuyền', 'Thận thuỷ chế Tâm hoả, khai khiếu tỉnh thần'),
  ('Bàng quang thấp nhiệt', 'Liệt khuyết', 'Khí hoá được thông hoạt'),
  ('Bàng quang thấp nhiệt', 'Côn lôn', 'Khử tà nhiệt ở bàng quang'),
  ('Bàng quang thấp nhiệt', 'Thận du', 'Chữa sỏi thận, niệu quản, bàng quang'),
  ('Bàng quang thấp nhiệt', 'Thuỷ đạo', 'Chữa sỏi thận, niệu quản, bàng quang'),
  ('Bàng quang thấp nhiệt', 'Trung cực', 'Mộ huyệt bàng quang, trị mọi bệnh bàng quang'),
  ('Bàng quang thấp nhiệt', 'Não hộ', 'Trị viêm cấp tính tiền liệt tuyến'),
  ('Bàng quang thấp nhiệt', 'Chí dương', 'Trị viêm cấp tính tiền liệt tuyến'),
  ('Bàng quang thấp nhiệt', 'Đảm du', 'Trị viêm cấp tính tiền liệt tuyến'),
  ('Bàng quang thấp nhiệt', 'Khúc cốt', 'Đặc trị bệnh tiền liệt tuyến'),
  ('Bàng quang thấp nhiệt', 'Hội âm', 'Trị bệnh nhị âm, chữa bí đái ỉa'),
  ('Phù nề dạ dầy', 'Can du', 'Điều chỉnh công năng tạng phủ qua bối du huyệt'),
  ('Phù nề dạ dầy', 'Đảm du', 'Điều chỉnh công năng tạng phủ qua bối du huyệt'),
  ('Phù nề dạ dầy', 'Tỳ du', 'Điều chỉnh công năng tạng phủ qua bối du huyệt'),
  ('Phù nề dạ dầy', 'Vị du', 'Điều chỉnh công năng tạng phủ qua bối du huyệt'),
  ('Phù nề dạ dầy', 'Trung quản', 'Huyệt chữa bệnh dạ dày truyền thống'),
  ('Phù nề dạ dầy', 'Lương môn', 'Huyệt chữa bệnh dạ dày truyền thống'),
  ('Phù nề dạ dầy', 'Nội quan', 'Huyệt chữa bệnh dạ dày truyền thống'),
  ('Phù nề dạ dầy', 'Túc tam lý', 'Huyệt chữa bệnh dạ dày truyền thống'),
  ('Bệnh đốt sống cổ', 'Ủy trung', 'Bổ, chữa đầu không cúi ngửa được'),
  ('Bệnh dị ứng', 'Đại chùy', 'Chữa dị ứng mẩn ngứa'),
  ('Bệnh dị ứng', 'Huyết hải', 'Chữa dị ứng mẩn ngứa'),
  ('Bệnh dị ứng', 'Khúc trì', 'Chữa dị ứng mẩn ngứa'),
  ('Bệnh dị ứng', 'Tam âm giao', 'Chữa dị ứng mẩn ngứa'),
  ('Bệnh dị ứng', 'Đại trường du', 'Chủ trị dị ứng mẩn ngứa mạn tính'),
  ('Bệnh dị ứng', 'Túc tam lý', 'Chữa dị ứng kèm đau bụng, ỉa chảy'),
  ('Bệnh dị ứng', 'Hợp cốc', 'Chữa ngực buồn bằn, thở gấp'),
  ('Bệnh dị ứng', 'Nội quan', 'Chữa ngực buồn bằn, thở gấp'),
  ('Bệnh dị ứng', 'Phế khu', 'Nhĩ châm chữa dị ứng'),
  ('Bệnh dị ứng', 'Thận thượng tuyến khu', 'Nhĩ châm chữa dị ứng'),
  ('Bệnh dị ứng', 'Thần môn', 'Nhĩ châm chữa dị ứng'),
  ('Bệnh dị ứng', 'Nội phân bí khu', 'Nhĩ châm chữa dị ứng'),
  ('Bệnh dị ứng', 'Phong môn', 'Chữa dị ứng mẩn ngứa'),
  ('Bệnh dị ứng', 'Liệt khuyết', 'Chữa dị ứng mẩn ngứa'),
  ('Bệnh dị ứng', 'Cách du', 'Chữa dị ứng mẩn ngứa'),
  ('Bệnh dị ứng', 'Kiên ngung', 'Chữa phong chẩn'),
  ('Bệnh dị ứng', 'Dương khê', 'Chữa phong chẩn'),
  ('Bệnh dị ứng', 'Bát phong', 'Chữa viêm bì thần kinh'),
  ('Bệnh dị ứng', 'Thượng bát phong', 'Chữa viêm bì thần kinh'),
  ('Bệnh dị ứng', 'Kiên nội lăng', 'Chữa phong nhiệt ẩn chẩn'),
  ('Bệnh dị ứng', 'Bách trùng sào', 'Chữa dị ứng mẩn ngứa'),
  ('Bệnh dị ứng', 'Định suyễn', 'Chữa dị ứng mẩn ngứa'),
  ('Bệnh dị ứng', 'Bách chủng phong', 'Chữa dị ứng mẩn ngứa'),
  ('Bệnh dị ứng', 'Chí dương', 'Chữa dị ứng, quá mẫn cảm viêm da'),
  ('Bệnh cảm cúm', 'Phong trì', 'Huyệt phương chủ, kích thích mạnh ra mồ hôi'),
  ('Bệnh cảm cúm', 'Hợp cốc', 'Huyệt phương chủ, kích thích mạnh ra mồ hôi'),
  ('Bệnh cảm cúm', 'Phục lưu', 'Huyệt phương chủ, kích thích mạnh ra mồ hôi'),
  ('Bệnh cảm cúm', 'Nghinh hương', 'Trị tắc mũi'),
  ('Bệnh cảm cúm', 'Khúc trì', 'Trị toàn thân đau buốt, sốt cao'),
  ('Bệnh cảm cúm', 'Thừa sơn', 'Trị toàn thân đau buốt'),
  ('Bệnh cảm cúm', 'Đại chùy', 'Trị sốt cao'),
  ('Bệnh cảm cúm', 'Thập tuyên', 'Trị sốt cao'),
  ('Bệnh cảm cúm', 'Thái dương', 'Trị đầu đau dữ dội'),
  ('Bệnh cảm cúm', 'Ấn đường', 'Trị đầu đau dữ dội'),
  ('Bệnh cảm cúm', 'Phế du', 'Trị ho hắng'),
  ('Bệnh cảm cúm', 'Xích trạch', 'Trị ho hắng'),
  ('Bệnh cảm cúm', 'Liệt khuyết', 'Trị ho hắng'),
  ('Bệnh cảm cúm', 'Thái uyên', 'Trị ho hắng'),
  ('Bệnh cảm cúm', 'Phù đột', 'Trị họng đau'),
  ('Bệnh cảm cúm', 'Thiếu thương', 'Trị họng đau, chích ra máu'),
  ('Bệnh cảm cúm', 'Nội quan', 'Trị quặn bụng buồn nôn'),
  ('Bệnh cảm cúm', 'Nội tị', 'Nhĩ châm trị cảm cúm'),
  ('Bệnh cảm cúm', 'Ngạch', 'Nhĩ châm trị cảm cúm'),
  ('Bệnh cảm cúm', 'Chẩm', 'Nhĩ châm trị cảm cúm'),
  ('Bệnh cảm cúm', 'Thận thượng tuyến', 'Nhĩ châm trị cảm cúm'),
  ('Bệnh cảm cúm', 'Bì chất hạ', 'Nhĩ châm trị cảm cúm'),
  ('Bệnh cảm cúm', 'Bách hội', 'Trị cảm mạo'),
  ('Bệnh cảm cúm', 'Ngoại quan', 'Trị cảm mạo'),
  ('Bệnh cảm cúm', 'Đào đạo', 'Trị cảm mạo'),
  ('Bệnh cảm cúm', 'Đại trữ', 'Trị cảm mạo'),
  ('Bệnh cảm cúm', 'Phong môn', 'Trị ho hắng, viêm phổi'),
  ('Bệnh cảm cúm', 'Trung xung', 'Trị ngoại cảm sốt cao'),
  ('Bệnh cảm cúm', 'Thương dương', 'Trị ngoại cảm sốt cao'),
  ('Bệnh cảm cúm', 'Tam thương', 'Trị cảm cúm'),
  ('Bệnh cảm cúm', 'Thập vương', 'Trị say nắng'),
  ('Bệnh cảm cúm', 'Nội nghinh hương', 'Trị say nắng')
) AS v(syndrome, huyet, y_nghia)
JOIN benh_dong_y b ON b.tieuket ILIKE v.syndrome
JOIN huyet_vi   h ON h.ten_huyet ILIKE v.huyet
WHERE p.id_benh = b.id AND p.id_huyet = h.id_huyet;

COMMIT;

-- RÀ SOÁT SAU KHI CHẠY:
--  SELECT c.tieuket "Thể kép", m.tieuket "Thể đơn" FROM benh_cau_thanh x
--    JOIN benh_dong_y c ON c.id=x.compound_id JOIN benh_dong_y m ON m.id=x.component_id
--    ORDER BY c.tieuket, x.thu_tu;
--  SELECT count(*) "Số huyệt có ý nghĩa" FROM phac_do_dieu_tri WHERE y_nghia_huyet IS NOT NULL;