// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface BaiThuoc {
  id: string;
  slug: string | null;
  status: string;
  xuat_xu?: string;
  tac_gia?: string;
  thanh_phan?: unknown;
  cach_dung?: PortableTextBlock[];
  tac_dung?: PortableTextBlock[];
  ghi_chu?: PortableTextBlock[];
  cho_index?: boolean;
  title: string;
  so_benh?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface BaiViet {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  content?: PortableTextBlock[];
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  ngay_dang?: string;
  ngay_cap_nhat?: string;
  tac_gia?: string;
  nguoi_duyet?: string;
  chuc_danh_nguoi_duyet?: string;
  cta?: string;
  tu_khoa?: unknown;
  faq?: unknown;
  nguon_tham_khao?: unknown;
  cho_index?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface BenhHoc {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  doi_chieu_benh_danh?: string;
  cho_index?: boolean;
  dai_cuong?: PortableTextBlock[];
  nguyen_nhan?: PortableTextBlock[];
  chan_doan?: PortableTextBlock[];
  dieu_tri?: PortableTextBlock[];
  benh_an?: PortableTextBlock[];
  tham_khao?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface ChamCuuTriBenh {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  dai_cuong?: PortableTextBlock[];
  nguyen_nhan?: PortableTextBlock[];
  trieu_chung?: PortableTextBlock[];
  dieu_tri?: PortableTextBlock[];
  cho_index?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface DuocLieu {
  id: string;
  slug: string | null;
  status: string;
  ten_khac?: string;
  ten_khoa_hoc?: string;
  ten_han?: string;
  ten_pinyin?: string;
  ho_khoa_hoc?: string;
  bo_phan_dung?: string;
  tinh?: string;
  vi?: string;
  quy_kinh?: string;
  lieu_dung?: string;
  cong_dung_tom_tat?: string;
  cong_dung_ds?: string;
  kieng_ky_ds?: string;
  anh_dai_dien?: string;
  mo_ta?: PortableTextBlock[];
  thanh_phan_hoa_hoc?: PortableTextBlock[];
  duoc_ly?: PortableTextBlock[];
  tinh_vi_quy_kinh?: PortableTextBlock[];
  nuoi_duong?: PortableTextBlock[];
  bao_che?: PortableTextBlock[];
  chu_tri?: PortableTextBlock[];
  don_thuoc?: PortableTextBlock[];
  xuat_xu?: PortableTextBlock[];
  tham_khao?: PortableTextBlock[];
  cho_index?: boolean;
  title: string;
  anh?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  so_bai_thuoc?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface HuyetVi {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  ma_huyet?: string;
  pho_huyet?: string;
  ghi_chu?: string;
  tham_khao?: string;
  cho_index?: boolean;
  y_nghia_ten?: PortableTextBlock[];
  dac_tinh?: PortableTextBlock[];
  vi_tri?: PortableTextBlock[];
  giai_phau?: PortableTextBlock[];
  tac_dung?: PortableTextBlock[];
  chu_tri?: PortableTextBlock[];
  cham_cuu?: PortableTextBlock[];
  xuat_xu?: PortableTextBlock[];
  ten_khac?: string;
  ten_han?: string;
  pinyin?: string;
  ten_anh?: string;
  anh?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  the_loai?: unknown;
  ma_cu?: number;
  so_benh?: number;
  benh_dung?: unknown;
  noi_dung_goc?: string;
  thu_tu_muc?: unknown;
  anh_duong_dan?: string;
  ma_gach?: string;
  chi_dinh?: unknown;
  slug_goc?: string;
  muc_goc?: unknown;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface KinhMach {
  id: string;
  slug: string | null;
  status: string;
  ten_khac?: string;
  ma?: string;
  dai_cuong?: PortableTextBlock[];
  dac_tinh?: PortableTextBlock[];
  van_hanh?: PortableTextBlock[];
  duong_chinh?: PortableTextBlock[];
  kinh_can?: PortableTextBlock[];
  kinh_biet?: PortableTextBlock[];
  lac_doc?: PortableTextBlock[];
  lac_ngang?: PortableTextBlock[];
  trieu_chung?: PortableTextBlock[];
  chu_tri?: PortableTextBlock[];
  dieu_tri?: PortableTextBlock[];
  huyet_ds?: string;
  tom_tat_huyet?: string;
  loai?: string;
  anh_tong_quat?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  anh_chinh?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  anh_can?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  anh_biet?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  anh_doc?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  anh_ngang?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  anh_so_do?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  title: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface NguonYVan {
  id: string;
  slug: string | null;
  status: string;
  title?: string;
  loai?: string;
  tac_gia?: string;
  nien_dai?: string;
  ten_khac?: string;
  ghi_chu?: string;
  lien_ket?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Trang {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    bai_thuoc: BaiThuoc;
    bai_viet: BaiViet;
    benh_hoc: BenhHoc;
    cham_cuu_tri_benh: ChamCuuTriBenh;
    duoc_lieu: DuocLieu;
    huyet_vi: HuyetVi;
    kinh_mach: KinhMach;
    nguon_y_van: NguonYVan;
    trang: Trang;
  }
}